/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_norman_app_jni_NativeUtil */

#ifndef _Included_com_norman_app_jni_NativeUtil
#define _Included_com_norman_app_jni_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_norman_app_jni_NativeUtil
 * Method:    hello
 * Signature: (SIJFDCZBLjava/lang/String;Ljava/lang/Object;[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_norman_app_jni_NativeUtil_hello
  (JNIEnv *, jobject, jshort, jint, jlong, jfloat, jdouble, jchar, jboolean, jbyte, jstring, jobject, jintArray);

/*
 * Class:     com_norman_app_jni_NativeUtil
 * Method:    accessStudent
 * Signature: (Lcom/norman/app/jni/Student;)V
 */
JNIEXPORT jobject JNICALL Java_com_norman_app_jni_NativeUtil_accessStudent
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
