/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com.norman.app_NativeUtil */

#ifndef _Included_com_norman_app_NativeUtil
#define _Included_com_norman_app_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com.norman.app_NativeUtil
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_norman_app_NativeUtil_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
