/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_norman_app_NativeUtil */

#ifndef _Included_com_norman_app_NativeUtil
#define _Included_com_norman_app_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_norman_app_NativeUtil
 * Method:    hello
 * Signature: (SIJFDCZBLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;[I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_norman_app_NativeUtil_hello
  (JNIEnv *, jclass, jshort, jint, jlong, jfloat, jdouble, jchar, jboolean, jbyte, jstring, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
